CONVERT_TO = rp2040_ce

LAYER_LOCK_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEYCODE_STRING_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes

MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
OLED_ENABLE     = yes
OLED_DRIVER     = ssd1306
LTO_ENABLE      = yes